--全局modifier初始化
LinkLuaModifier( "modifier_gem_shuangren_fu","ability/modifier/modifier_gem_shuangren_fu", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_chainmail","ability/modifier/modifier_gem_chainmail", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_platemail","ability/modifier/modifier_gem_platemail", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_huiguang_fu","ability/modifier/modifier_gem_huiguang_fu", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_budao_fu","ability/modifier/modifier_gem_budao_fu", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_shixue_lua","ability/modifier/modifier_gem_shixue_lua",LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_xunjizhijian_lua","ability/modifier/modifier_gem_xunjizhijian_lua",LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_zuizhongzhijian_lua","ability/modifier/modifier_gem_zuizhongzhijian_lua",LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_god_left_hand","ability/modifier/modifier_gem_god_left_hand", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_god_right_hand","ability/modifier/modifier_gem_god_right_hand", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_god_hand","ability/modifier/modifier_gem_god_hand", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_bow_of_aeolus","ability/modifier/modifier_gem_bow_of_aeolus", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_arrow_of_aeolus","ability/modifier/modifier_gem_arrow_of_aeolus", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_power_of_aeolus","ability/modifier/modifier_gem_power_of_aeolus", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_blacksmith_right_wristbands","ability/modifier/modifier_gem_blacksmith_right_wristbands", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_blacksmith_left_wristbands","ability/modifier/modifier_gem_blacksmith_left_wristbands", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_blacksmith_power","ability/modifier/modifier_gem_blacksmith_power", LUA_MODIFIER_MOTION_NONE )

LinkLuaModifier("modifier_gem_die_venom", "ability/modifier/modifier_gem_die_venom", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_raging_fire_interrogate", "ability/modifier/modifier_gem_raging_fire_interrogate", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_void_lock", "ability/modifier/modifier_gem_void_lock", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_earth_burst", "ability/modifier/modifier_gem_earth_burst", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_shadow_quiet", "ability/modifier/modifier_gem_shadow_quiet", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_Ice_storm", "ability/modifier/modifier_gem_Ice_storm", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_gem_bubaizhidun", "ability/modifier/modifier_gem_bubaizhidun", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_yuanshemoshi", "ability/modifier/modifier_gem_yuanshemoshi", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_liliangcuncu_huang", "ability/modifier/modifier_gem_liliangcuncu_huang", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_liliangcuncu_zi", "ability/modifier/modifier_gem_liliangcuncu_zi", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_liliangcuncu", "ability/modifier/modifier_gem_liliangcuncu", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_xiaozhiliao", "ability/modifier/modifier_gem_xiaozhiliao", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_zhongzhiliao", "ability/modifier/modifier_gem_zhongzhiliao", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_dazhiliao", "ability/modifier/modifier_gem_dazhiliao", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_busishengbei", "ability/modifier/modifier_gem_busishengbei", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_yinxuejian", "ability/modifier/modifier_gem_yinxuejian", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_yongmengmoshi", "ability/modifier/modifier_gem_yongmengmoshi", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_tanlanmianju", "ability/modifier/modifier_gem_tanlanmianju", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_emoqiyue", "ability/modifier/modifier_gem_emoqiyue", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_budengzhiduihuan", "ability/modifier/modifier_gem_budengzhiduihuan", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_gem_yongmengzhiren_xiao", "ability/modifier/modifier_gem_yongmengzhiren_xiao", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_yongmengzhiren_zhong", "ability/modifier/modifier_gem_yongmengzhiren_zhong", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_yongmengzhiren_da", "ability/modifier/modifier_gem_yongmengzhiren_da", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_yongmengzhiren_heimo", "ability/modifier/modifier_gem_yongmengzhiren_heimo", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_canbaizhiren", "ability/modifier/modifier_gem_canbaizhiren", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_shihunshengbei", "ability/modifier/modifier_gem_shihunshengbei", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_shufuzhiren", "ability/modifier/modifier_gem_shufuzhiren", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_duohunfazhang", "ability/modifier/modifier_gem_duohunfazhang", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_gem_devil_head", "ability/modifier/modifier_gem_devil_head", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_devil_left_hand", "ability/modifier/modifier_gem_devil_left_hand", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_devil_right_hand", "ability/modifier/modifier_gem_devil_right_hand", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_devil_left_foot", "ability/modifier/modifier_gem_devil_left_foot", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_devil_right_foot", "ability/modifier/modifier_gem_devil_right_foot", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_devilzhili", "ability/modifier/modifier_gem_devilzhili", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_gangtieheji", "ability/modifier/modifier_gem_gangtieheji", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_pinbenshishadewo", "ability/modifier/modifier_gem_pinbenshishadewo", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_yezhendebuyaole", "ability/modifier/modifier_gem_yezhendebuyaole", LUA_MODIFIER_MOTION_NONE)

--箭魂修炼
LinkLuaModifier("modifier_arrowSoul_meditation", "ability/modifier/modifier_arrowSoul_meditation", LUA_MODIFIER_MOTION_NONE)