--全局modifier初始化
LinkLuaModifier( "modifier_gem_shuangren_fu","ability/modifier/modifier_gem_shuangren_fu", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_chainmail","ability/modifier/modifier_gem_chainmail", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_platemail","ability/modifier/modifier_gem_platemail", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_huiguang_fu","ability/modifier/modifier_gem_huiguang_fu", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_budao_fu","ability/modifier/modifier_gem_budao_fu", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_shixue_lua","ability/modifier/modifier_gem_shixue_lua",LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_xunjizhijian_lua","ability/modifier/modifier_gem_xunjizhijian_lua",LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_zuizhongzhijian_lua","ability/modifier/modifier_gem_zuizhongzhijian_lua",LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_god_left_hand","ability/modifier/modifier_gem_god_left_hand", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_god_right_hand","ability/modifier/modifier_gem_god_right_hand", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_god_hand","ability/modifier/modifier_gem_god_hand", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_bow_of_aeolus","ability/modifier/modifier_gem_bow_of_aeolus", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_arrow_of_aeolus","ability/modifier/modifier_gem_arrow_of_aeolus", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_power_of_aeolus","ability/modifier/modifier_gem_power_of_aeolus", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_blacksmith_right_wristbands","ability/modifier/modifier_gem_blacksmith_right_wristbands", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_blacksmith_left_wristbands","ability/modifier/modifier_gem_blacksmith_left_wristbands", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_blacksmith_power","ability/modifier/modifier_gem_blacksmith_power", LUA_MODIFIER_MOTION_NONE )

LinkLuaModifier("modifier_gem_die_venom", "ability/modifier/modifier_gem_die_venom", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_raging_fire_interrogate", "ability/modifier/modifier_gem_raging_fire_interrogate", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_void_lock", "ability/modifier/modifier_gem_void_lock", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_earth_burst", "ability/modifier/modifier_gem_earth_burst", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_shadow_quiet", "ability/modifier/modifier_gem_shadow_quiet", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_Ice_storm", "ability/modifier/modifier_gem_Ice_storm", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_gem_bubaizhidun", "ability/modifier/modifier_gem_bubaizhidun", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_yuanshemoshi", "ability/modifier/modifier_gem_yuanshemoshi", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_liliangcuncu_huang", "ability/modifier/modifier_gem_liliangcuncu_huang", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_liliangcuncu_zi", "ability/modifier/modifier_gem_liliangcuncu_zi", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_liliangcuncu", "ability/modifier/modifier_gem_liliangcuncu", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_xiaozhiliao", "ability/modifier/modifier_gem_xiaozhiliao", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_zhongzhiliao", "ability/modifier/modifier_gem_zhongzhiliao", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_dazhiliao", "ability/modifier/modifier_gem_dazhiliao", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_busishengbei", "ability/modifier/modifier_gem_busishengbei", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_yinxuejian", "ability/modifier/modifier_gem_yinxuejian", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_yongmengmoshi", "ability/modifier/modifier_gem_yongmengmoshi", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_tanlanmianju", "ability/modifier/modifier_gem_tanlanmianju", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_emoqiyue", "ability/modifier/modifier_gem_emoqiyue", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_budengzhiduihuan", "ability/modifier/modifier_gem_budengzhiduihuan", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_gem_yongmengzhiren_xiao", "ability/modifier/modifier_gem_yongmengzhiren_xiao", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_yongmengzhiren_zhong", "ability/modifier/modifier_gem_yongmengzhiren_zhong", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_yongmengzhiren_da", "ability/modifier/modifier_gem_yongmengzhiren_da", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_yongmengzhiren_heimo", "ability/modifier/modifier_gem_yongmengzhiren_heimo", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_canbaizhiren", "ability/modifier/modifier_gem_canbaizhiren", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_shihunshengbei", "ability/modifier/modifier_gem_shihunshengbei", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_shufuzhiren", "ability/modifier/modifier_gem_shufuzhiren", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_duohunfazhang", "ability/modifier/modifier_gem_duohunfazhang", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_gem_devil_head", "ability/modifier/modifier_gem_devil_head", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_devil_left_hand", "ability/modifier/modifier_gem_devil_left_hand", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_devil_right_hand", "ability/modifier/modifier_gem_devil_right_hand", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_devil_left_foot", "ability/modifier/modifier_gem_devil_left_foot", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_devil_right_foot", "ability/modifier/modifier_gem_devil_right_foot", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_devilzhili", "ability/modifier/modifier_gem_devilzhili", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_gangtieheji", "ability/modifier/modifier_gem_gangtieheji", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_pinbenshishadewo", "ability/modifier/modifier_gem_pinbenshishadewo", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gem_yezhendebuyaole", "ability/modifier/modifier_gem_yezhendebuyaole", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier( "modifier_gem_tiangoubudehaosi", "ability/modifier/modifier_gem_tiangoubudehaosi.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_zhiliao_taozhuang", "ability/modifier/modifier_gem_zhiliao_taozhuang.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_hujia_taozhuang", "ability/modifier/modifier_gem_hujia_taozhuang.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_fuhuoshijian", "ability/modifier/modifier_gem_fuhuoshijian.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_shanghaizengfu_1", "ability/modifier/modifier_gem_shanghaizengfu_1.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_shanghaizengfu_2", "ability/modifier/modifier_gem_shanghaizengfu_2.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_shanghaizengfu_3", "ability/modifier/modifier_gem_shanghaizengfu_3.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_shanghaizengfu_4", "ability/modifier/modifier_gem_shanghaizengfu_4.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_shanghaizengfu_taozhuang", "ability/modifier/modifier_gem_shanghaizengfu_taozhuang.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_tanlan", "ability/modifier/modifier_gem_tanlan.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_zuanshi_touzi", "ability/modifier/modifier_gem_zuanshi_touzi.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_huihedashang", "ability/modifier/modifier_gem_huihedashang.lua", LUA_MODIFIER_MOTION_NONE )

--箭魂修炼
LinkLuaModifier("modifier_arrowSoul_meditation", "ability/modifier/modifier_arrowSoul_meditation", LUA_MODIFIER_MOTION_NONE)
--贪婪加移动速技能
LinkLuaModifier( "modifier_create_monster_move_speed", "ability/creatures/create_monster_move_speed.lua", LUA_MODIFIER_MOTION_NONE )
-- 怪物释放技能AI
LinkLuaModifier("modifier_cooldown_ai", "ability/modifier/modifier_cooldown_ai", LUA_MODIFIER_MOTION_NONE)
--深渊模式减伤光环
LinkLuaModifier( "modifier_abyss_jianshang", "ability/modifier/modifier_abyss_jianshang.lua", LUA_MODIFIER_MOTION_NONE )
-- 深渊Boss随机buff
LinkLuaModifier("modifier_abyssBoss_DeBuff_and_Buff", "ability/modifier/modifier_abyssBoss_DeBuff_and_Buff", LUA_MODIFIER_MOTION_NONE)
--自闭移速modifier
LinkLuaModifier( "modifei_monster_movespeed", "ability/creatures/modifei_monster_movespeed.lua", LUA_MODIFIER_MOTION_NONE )
--减少移速modifier
LinkLuaModifier( "modifier_stop_move", "ability/creatures/modifier_stop_move.lua", LUA_MODIFIER_MOTION_NONE )
--彩蛋boss
LinkLuaModifier( "modifier_caidan_boss", "ability/modifier/modifier_caidan_boss.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_caidan_boss_2", "ability/modifier/modifier_caidan_boss_2.lua", LUA_MODIFIER_MOTION_NONE )
-- 特殊宝物的套装效果
LinkLuaModifier("modifier_gem_special_buff", "ability/modifier/modifier_gem_special_buff", LUA_MODIFIER_MOTION_NONE)
-- 恶魔宝物
LinkLuaModifier( "modifier_gem_ripple_devil", "ability/modifier/devil/modifier_gem_ripple_devil", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_as_divine_wrath", "ability/modifier/devil/modifier_gem_as_divine_wrath", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_ares_meaning", "ability/modifier/devil/modifier_gem_ares_meaning", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_look_my_health", "ability/modifier/devil/modifier_gem_look_my_health", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_look_my_armor", "ability/modifier/devil/modifier_gem_look_my_armor", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_special_suit_buff", "ability/modifier/devil/modifier_gem_special_suit_buff", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_the_power_of_the_undead", "ability/modifier/devil/modifier_gem_the_power_of_the_undead", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_strength_explode", "ability/modifier/devil/modifier_gem_strength_explode", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_agility_explode", "ability/modifier/devil/modifier_gem_agility_explode", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_intelligence_explode", "ability/modifier/devil/modifier_gem_intelligence_explode", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_demonic_contract_true", "ability/modifier/devil/modifier_gem_demonic_contract_true", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_greed_mask_true", "ability/modifier/devil/modifier_gem_greed_mask_true", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_super_storage_yellow", "ability/modifier/devil/modifier_gem_super_storage_yellow", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_super_storage_purple", "ability/modifier/devil/modifier_gem_super_storage_purple", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_devil_greed", "ability/modifier/devil/modifier_gem_devil_greed", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_demon_summoned", "ability/modifier/devil/modifier_gem_demon_summoned", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_investment_in_secret", "ability/modifier/devil/modifier_gem_investment_in_secret", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_eats_the_soul_god_cup", "ability/modifier/devil/modifier_gem_eats_the_soul_god_cup", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_falling_of_sword", "ability/modifier/devil/modifier_gem_falling_of_sword", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_devil_add_strength", "ability/modifier/devil/modifier_gem_devil_add_strength", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_devil_add_agility", "ability/modifier/devil/modifier_gem_devil_add_agility", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_devil_add_intelligence", "ability/modifier/devil/modifier_gem_devil_add_intelligence", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_devil_chosen_people", "ability/modifier/devil/modifier_gem_devil_chosen_people", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_devil_drinking_blood_jian_of_soul", "ability/modifier/devil/modifier_gem_devil_drinking_blood_jian_of_soul", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_devil_start_all_over_again", "ability/modifier/devil/modifier_gem_devil_start_all_over_again", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_devil_demon_game", "ability/modifier/devil/modifier_gem_devil_demon_game", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_super_storage_yellow_purple_additional_attr", "ability/modifier/devil/modifier_gem_super_storage_yellow_purple_additional_attr", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_devil_greed_additional", "ability/modifier/devil/modifier_gem_devil_greed_additional", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_investment_in_secret_additional", "ability/modifier/devil/modifier_gem_investment_in_secret_additional", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_eats_the_soul_god_cup_additional", "ability/modifier/devil/modifier_gem_eats_the_soul_god_cup_additional", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_devil_chosen_people_additional", "ability/modifier/devil/modifier_gem_devil_chosen_people_additional", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_devil_drinking_blood_jian_of_soul_additional", "ability/modifier/devil/modifier_gem_devil_drinking_blood_jian_of_soul_additional", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_strength_explode_additional", "ability/modifier/devil/modifier_gem_strength_explode_additional", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_agility_explode_additional", "ability/modifier/devil/modifier_gem_agility_explode_additional", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_intelligence_explode_additional", "ability/modifier/devil/modifier_gem_intelligence_explode_additional", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_ripple_devil_additional_attr", "ability/modifier/devil/modifier_gem_ripple_devil_additional_attr", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_as_divine_wrath_additional_attr", "ability/modifier/devil/modifier_gem_as_divine_wrath_additional_attr", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_wind_howling_additional_attr", "ability/modifier/devil/modifier_gem_wind_howling_additional_attr", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_ares_meaning_additional_attr", "ability/modifier/devil/modifier_gem_ares_meaning_additional_attr", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_look_my_health_OnAttackLanded", "ability/modifier/devil/modifier_gem_look_my_health_OnAttackLanded", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_look_my_armor_OnAttackLanded", "ability/modifier/devil/modifier_gem_look_my_armor_OnAttackLanded", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_special_suit_buff_OnAttackLanded", "ability/modifier/devil/modifier_gem_special_suit_buff_OnAttackLanded", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_greed_mask_true_OnAttackLanded", "ability/modifier/devil/modifier_gem_greed_mask_true_OnAttackLanded", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_wind_howling", "ability/modifier/devil/modifier_gem_wind_howling", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_falling_of_sword_additional", "ability/modifier/devil/modifier_gem_falling_of_sword_additional", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_devil_subtract_damage", "ability/modifier/devil/modifier_gem_devil_subtract_damage", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_gem_memnoch_the_devil_true", "ability/modifier/devil/modifier_gem_memnoch_the_devil_true", LUA_MODIFIER_MOTION_NONE )