return {
	particle = {
		"particles/econ/items/axe/ti9_jungle_axe/ti9_jungle_axe_misc_ambient_flame.vpcf",
		"particles/ui/ui_rank_tier_levelup.vpcf",
		"particles/econ/events/ti8/hero_levelup_ti8.vpcf",
		"particles/units/heroes/hero_phantom_assassin/phantom_assassin_stifling_dagger.vpcf",
		"particles/units/heroes/hero_phantom_assassin/phantom_assassin_attack_blur.vpcf",
		"particles/units/heroes/hero_phantom_assassin/phantom_assassin_attack_blur_b.vpcf",
		"particles/units/heroes/hero_lone_druid/lone_druid_attack_start.vpcf",
		"particles/units/heroes/hero_rubick/rubick_attack_blur_right_to_left_01.vpcf",
		"particles/units/heroes/hero_rubick/rubick_attack_blur_right_to_left_02.vpcf",
		"particles/units/heroes/hero_rubick/rubick_attack_blur_left_to_right_01.vpcf",
		"particles/units/heroes/hero_doom_bringer/doom_weapon_blur.vpcf",
		"particles/units/heroes/hero_doom_bringer/doom_weapon_blurb.vpcf",
		"particles/units/heroes/hero_zuus/zuus_arc_lightning.vpcf",
		"particles/units/heroes/hero_nevermore/nevermore_shadowraze.vpcf",
		"particles/econ/items/bristleback/bristle_spikey_spray/bristle_spikey_quill_spray.vpcf",
		"particles/heroes/thtd_junko/ability_junko_03.vpcf",
		"particles/units/heroes/hero_ursa/ursa_earthshock.vpcf",
		"particles/units/heroes/hero_elder_titan/elder_titan_echo_stomp_magical.vpcf",
		"particles/units/heroes/hero_lina/lina_spell_light_strike_array.vpcf",
		"particles/heroes/mouko/ability_mokou_01_boom.vpcf",
		"particles/thd2/heroes/utsuho/ability_utsuho01_effect.vpcf",
		"particles/units/heroes/hero_ogre_magi/ogre_magi_fireblast_cast.vpcf",
		"particles/heroes/humei/ability_humei_011_ice_c.vpcf",
		"particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/maiden_crystal_nova_cowlofice.vpcf",
		"particles/econ/items/keeper_of_the_light/kotl_ti10_immortal/kotl_ti10_blinding_light.vpcf",
		"particles/units/heroes/hero_faceless_void/faceless_void_time_lock_bash.vpcf",
		"particles/econ/courier/courier_cluckles/patchouli_sorcererstone.vpcf",
		"particles/econ/events/ti8/bottle_ti8.vpcf",
		"particles/econ/events/ti6/mekanism_ti6.vpcf",
		"particles/ambient/ambient1.vpcf",
		"particles/diy_particles/wing1.vpcf",
		"particles/diy_particles/ambient3.vpcf",
		"particles/diy_particles/ambient4.vpcf",
		"particles/diy_particles/ambient5.vpcf",
		"particles/diy_particles/ambient6.vpcf",
		"particles/diy_particles/ambient7.vpcf",
		"particles/diy_particles/ambient8.vpcf",
		"particles/diy_particles/screen_arcane.vpcf",
		"particles/diy_particles/ambient12.vpcf",
		"particles/econ/items/templar_assassin/templar_assassin_focal/ta_focal_base_attack.vpcf",
		"particles/radiant_fx2/fs_altar_ascension.vpcf",
		"models/npc/shinai/shinai.vmdl",
	},

	soundfile = {
		"sounds/ui/menu/trophy_levelup.vsnd",
		"sounds/jinbi.vsnd",
		"soundevents/custom_sounds.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_ursa.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_invoker.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_ogre_magi.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_omniknight.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_dazzle.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_doombringer.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_earthshaker.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_venomancer.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_windrunner.vsndevts",
		-- 新加天赋声音
		"soundevents/game_sounds_heroes/game_sounds_arc_warden.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_vengefulspirit.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_nevermore.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_gyrocopter.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_tinker.vsndevts",
	},

	model = {
		"models/npc/d2/d2.vmdl",
		"models/npc/d3/d3.vmdl",
		"models/npc/d4/d4.vmdl",
		"models/npc/d5/d5.vmdl",
		"models/npc/d6/d6.vmdl",
		"models/npc/d7/d7.vmdl",
		"models/npc/d8/d8.vmdl",
		"models/npc/d9/d9.vmdl",
		"models/heroes/troll_warlord/leimi.vmdl",
		"models/npc/luoli/luoli.vmdl",
	}

}